wandb_version: 1

raw_dir:
  desc: null
  value: melanoma_data/
kernel_type:
  desc: null
  value: gaussian
threshold:
  desc: null
  value: 5.0e-05
hidden_dim:
  desc: null
  value: 20
num_layers:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.001
wd:
  desc: null
  value: 0.003
num_epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 64
gpu:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724878295.494835
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.9.17
      5: 0.15.8
      8:
      - 5
