wandb_version: 1

raw_dir:
  desc: null
  value: melanoma_data
kernel_type:
  desc: null
  value: gaussian
threshold:
  desc: null
  value: 5.0e-05
hidden_dim:
  desc: null
  value: 300
num_layers:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.01
wd:
  desc: null
  value: 0.0003
num_epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 16
gpu:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724337439
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.17.7
      8:
      - 3
      - 5
      13: windows-amd64
